# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cbbfca2fd390e3b6ac9963cef2e9aa51"
application_url = "https://dista-app.onrender.com"
embedded = true
name = "Dista App - Rajah Ayurveda"
handle = "dista-app-rajah-ayurveda"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "distaxstaging.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_checkouts,read_customers,read_orders,read_payment_customizations,read_products,read_translations,read_validations,write_checkouts,write_payment_customizations,write_products,write_validations"

[auth]
redirect_urls = [
  "https://dista-app.onrender.com/auth/callback",
  "https://dista-app.onrender.com/auth/shopify/callback",
  "https://dista-app.onrender.com/api/auth/callback"
]

[app_proxy]
url = "https://dista-app.onrender.com"
subpath = "rvpp"
prefix = "a"

[pos]
embedded = false
